- name: Create namespace 
  k8s:
    state: present
    kind: Namespace 
    name: kasten-io 

- name: Add helm repo
  kubernetes.core.helm_repository:
    name: kasten 
    repo_url: "{{ helm_chart_url }}"

- name: Install k10 Chart
  kubernetes.core.helm:
    name: k10 
    release_namespace: kasten-io
    chart_ref: kasten/k10
    values:
      scc.creater: true
      route.enabled: true
      route.tls.enabled: true
      auth.openshift.enabled: true
      auth.openshift.serviceAccount: k10-dex-sa
      auth.openshift.insecureCA: true


